//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MSDNSWebAdmin.AppCode
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DNSAdminEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DNSAdminEntities object using the connection string found in the 'DNSAdminEntities' section of the application configuration file.
        /// </summary>
        public DNSAdminEntities() : base("name=DNSAdminEntities", "DNSAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DNSAdminEntities object.
        /// </summary>
        public DNSAdminEntities(string connectionString) : base(connectionString, "DNSAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DNSAdminEntities object.
        /// </summary>
        public DNSAdminEntities(EntityConnection connection) : base(connection, "DNSAdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DNSServer> DNSServers
        {
            get
            {
                if ((_DNSServers == null))
                {
                    _DNSServers = base.CreateObjectSet<DNSServer>("DNSServers");
                }
                return _DNSServers;
            }
        }
        private ObjectSet<DNSServer> _DNSServers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditRecord> AuditRecords
        {
            get
            {
                if ((_AuditRecords == null))
                {
                    _AuditRecords = base.CreateObjectSet<AuditRecord>("AuditRecords");
                }
                return _AuditRecords;
            }
        }
        private ObjectSet<AuditRecord> _AuditRecords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DNSServers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDNSServers(DNSServer dNSServer)
        {
            base.AddObject("DNSServers", dNSServer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditRecords(AuditRecord auditRecord)
        {
            base.AddObject("AuditRecords", auditRecord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNSAdmin", Name="AuditRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditRecord object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="timestampUTC">Initial value of the TimestampUTC property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="server">Initial value of the Server property.</param>
        /// <param name="clientIP">Initial value of the ClientIP property.</param>
        public static AuditRecord CreateAuditRecord(global::System.Guid id, global::System.String username, global::System.DateTime timestampUTC, global::System.String text, global::System.String type, global::System.String server, global::System.String clientIP)
        {
            AuditRecord auditRecord = new AuditRecord();
            auditRecord.Id = id;
            auditRecord.Username = username;
            auditRecord.TimestampUTC = timestampUTC;
            auditRecord.Text = text;
            auditRecord.Type = type;
            auditRecord.Server = server;
            auditRecord.ClientIP = clientIP;
            return auditRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimestampUTC
        {
            get
            {
                return _TimestampUTC;
            }
            set
            {
                OnTimestampUTCChanging(value);
                ReportPropertyChanging("TimestampUTC");
                _TimestampUTC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimestampUTC");
                OnTimestampUTCChanged();
            }
        }
        private global::System.DateTime _TimestampUTC;
        partial void OnTimestampUTCChanging(global::System.DateTime value);
        partial void OnTimestampUTCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Server
        {
            get
            {
                return _Server;
            }
            set
            {
                OnServerChanging(value);
                ReportPropertyChanging("Server");
                _Server = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Server");
                OnServerChanged();
            }
        }
        private global::System.String _Server;
        partial void OnServerChanging(global::System.String value);
        partial void OnServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientIP
        {
            get
            {
                return _ClientIP;
            }
            set
            {
                OnClientIPChanging(value);
                ReportPropertyChanging("ClientIP");
                _ClientIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientIP");
                OnClientIPChanged();
            }
        }
        private global::System.String _ClientIP;
        partial void OnClientIPChanging(global::System.String value);
        partial void OnClientIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zone
        {
            get
            {
                return _Zone;
            }
            set
            {
                OnZoneChanging(value);
                ReportPropertyChanging("Zone");
                _Zone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zone");
                OnZoneChanged();
            }
        }
        private global::System.String _Zone;
        partial void OnZoneChanging(global::System.String value);
        partial void OnZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecordName
        {
            get
            {
                return _RecordName;
            }
            set
            {
                OnRecordNameChanging(value);
                ReportPropertyChanging("RecordName");
                _RecordName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecordName");
                OnRecordNameChanged();
            }
        }
        private global::System.String _RecordName;
        partial void OnRecordNameChanging(global::System.String value);
        partial void OnRecordNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNSAdmin", Name="DNSServer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DNSServer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DNSServer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="serverName">Initial value of the ServerName property.</param>
        public static DNSServer CreateDNSServer(global::System.Guid id, global::System.String serverName)
        {
            DNSServer dNSServer = new DNSServer();
            dNSServer.Id = id;
            dNSServer.ServerName = serverName;
            return dNSServer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ServerName
        {
            get
            {
                return _ServerName;
            }
            set
            {
                OnServerNameChanging(value);
                ReportPropertyChanging("ServerName");
                _ServerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ServerName");
                OnServerNameChanged();
            }
        }
        private global::System.String _ServerName;
        partial void OnServerNameChanging(global::System.String value);
        partial void OnServerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();

        #endregion
    
    }

    #endregion
    
}
